import { prisma } from "@/lib/prisma";

const SUBMISSION_DEADLINE_KEY = "SUBMISSION_DEADLINE";
const SITE_VISIT_KEY = "SITE_VISIT";
const AWARD_DATE_KEY = "AWARD_DATE";

/**
 * Keeps the auto-tracked deadline/tasks in sync with a project's three key dates:
 * - Submission deadline -> a Deadline (the one hard date that must not be missed)
 * - Site visit / Award date -> ordinary Tasks tied directly to the project
 * Called after every project create/update so the two views never drift.
 */
export async function syncProjectDates(projectId: string) {
  const project = await prisma.project.findUnique({ where: { id: projectId } });
  if (!project) return;

  if (project.submissionDeadline) {
    await prisma.task.upsert({
      where: { projectId_autoKey: { projectId, autoKey: SUBMISSION_DEADLINE_KEY } },
      update: {
        title: `Submit tender: ${project.title}`,
        dueDate: project.submissionDeadline,
      },
      create: {
        title: `Submit tender: ${project.title}`,
        dueDate: project.submissionDeadline,
        projectId,
        autoGenerated: true,
        autoKey: SUBMISSION_DEADLINE_KEY,
      },
    });
  } else {
    await prisma.task.deleteMany({ where: { projectId, autoKey: SUBMISSION_DEADLINE_KEY } });
  }

  if (project.siteVisitDate) {
    await prisma.subtask.upsert({
      where: { projectId_autoKey: { projectId, autoKey: SITE_VISIT_KEY } },
      update: {
        title: `Site visit: ${project.title}`,
        dueDate: project.siteVisitDate,
      },
      create: {
        title: `Site visit: ${project.title}`,
        dueDate: project.siteVisitDate,
        projectId,
        autoGenerated: true,
        autoKey: SITE_VISIT_KEY,
      },
    });
  } else {
    await prisma.subtask.deleteMany({ where: { projectId, autoKey: SITE_VISIT_KEY } });
  }

  if (project.awardDate) {
    await prisma.subtask.upsert({
      where: { projectId_autoKey: { projectId, autoKey: AWARD_DATE_KEY } },
      update: {
        title: `Award date: ${project.title}`,
        dueDate: project.awardDate,
      },
      create: {
        title: `Award date: ${project.title}`,
        dueDate: project.awardDate,
        projectId,
        autoGenerated: true,
        autoKey: AWARD_DATE_KEY,
      },
    });
  } else {
    await prisma.subtask.deleteMany({ where: { projectId, autoKey: AWARD_DATE_KEY } });
  }
}

const TARGET_COMPLETION_KEY = "TARGET_COMPLETION";

/**
 * Keeps a PM project's target completion date mirrored as an auto-tracked deadline,
 * so it surfaces on the PM Deadlines page without duplicate manual entry.
 * Called after every PM project create/update so the two views never drift.
 */
export async function syncPmProjectDates(pmProjectId: string) {
  const project = await prisma.pmProject.findUnique({ where: { id: pmProjectId } });
  if (!project) return;

  if (project.targetEndDate) {
    await prisma.task.upsert({
      where: { pmProjectId_autoKey: { pmProjectId, autoKey: TARGET_COMPLETION_KEY } },
      update: {
        title: `Target completion: ${project.title}`,
        dueDate: project.targetEndDate,
      },
      create: {
        title: `Target completion: ${project.title}`,
        dueDate: project.targetEndDate,
        pmProjectId,
        scope: "PM",
        autoGenerated: true,
        autoKey: TARGET_COMPLETION_KEY,
      },
    });
  } else {
    await prisma.task.deleteMany({ where: { pmProjectId, autoKey: TARGET_COMPLETION_KEY } });
  }
}
