import Link from "next/link";
import { format, isPast, isToday, startOfDay } from "date-fns";
import { Calendar, Sparkles } from "lucide-react";
import type { DeadlineRow } from "./types";

export default function GridView({
  deadlines,
}: {
  deadlines: (DeadlineRow & { _count: { taskNotes: number } })[];
}) {
  if (deadlines.length === 0) {
    return (
      <p className="rounded-xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-400 shadow-sm">
        Nothing here.
      </p>
    );
  }

  return (
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {deadlines.map((deadline) => {
        const due = deadline.dueDate ? startOfDay(deadline.dueDate) : null;
        const overdue = due && deadline.status === "OPEN" && isPast(due) && !isToday(due);
        const dueToday = due && isToday(due);
        const doneCount = deadline.subtasks.filter((s) => s.status === "DONE").length;

        return (
          <Link
            key={deadline.id}
            href={`/deadlines/${deadline.id}`}
            className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm transition hover:shadow-md"
          >
            <div className="mb-2 flex items-start justify-between gap-2">
              <p
                className={`line-clamp-2 text-sm font-medium ${
                  deadline.status === "DONE" ? "text-slate-400 line-through" : "text-slate-900"
                }`}
              >
                {deadline.title}
              </p>
              {deadline.autoGenerated && <Sparkles size={13} className="shrink-0 text-slate-300" />}
            </div>
            {deadline.project && (
              <p className="mb-2 truncate text-xs text-slate-500">{deadline.project.title}</p>
            )}
            <div className="flex items-center justify-between">
              {deadline.subtasks.length > 0 ? (
                <span className="text-xs text-slate-400">
                  {doneCount}/{deadline.subtasks.length} tasks
                </span>
              ) : (
                <span />
              )}
              {due && (
                <span
                  className={`flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium ${
                    overdue
                      ? "bg-red-50 text-red-700"
                      : dueToday
                        ? "bg-amber-50 text-amber-700"
                        : "bg-slate-100 text-slate-600"
                  }`}
                >
                  <Calendar size={11} />
                  {format(due, "MMM d")}
                </span>
              )}
            </div>
          </Link>
        );
      })}
    </div>
  );
}
