-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "Trade" ADD VALUE 'AV_IT_SYSTEMS';
ALTER TYPE "Trade" ADD VALUE 'ACOUSTICS_CEILINGS';
ALTER TYPE "Trade" ADD VALUE 'ARCHITECTURE_INTERIOR_DESIGN';
ALTER TYPE "Trade" ADD VALUE 'ART_ACCESSORIES';
ALTER TYPE "Trade" ADD VALUE 'AUTOMOTIVE';
ALTER TYPE "Trade" ADD VALUE 'AWNINGS_SHADING';
ALTER TYPE "Trade" ADD VALUE 'BUILDING_AUTOMATION_CONTROLS';
ALTER TYPE "Trade" ADD VALUE 'BUILDING_CONTRACTING';
ALTER TYPE "Trade" ADD VALUE 'BUILDING_MATERIALS_TRADING';
ALTER TYPE "Trade" ADD VALUE 'CARPETS_RUGS';
ALTER TYPE "Trade" ADD VALUE 'CLEANING_FACILITIES_MANAGEMENT';
ALTER TYPE "Trade" ADD VALUE 'CONCRETE_SCREED';
ALTER TYPE "Trade" ADD VALUE 'CURTAINS_BLINDS';
ALTER TYPE "Trade" ADD VALUE 'DOORS_SHUTTERS';
ALTER TYPE "Trade" ADD VALUE 'ELECTRICAL_SUPPLIES_SERVICES';
ALTER TYPE "Trade" ADD VALUE 'ENERGY_SUSTAINABILITY';
ALTER TYPE "Trade" ADD VALUE 'ENGINEERING_CONSULTANCY';
ALTER TYPE "Trade" ADD VALUE 'EQUIPMENT_RENTAL';
ALTER TYPE "Trade" ADD VALUE 'FACADES_CURTAIN_WALLING';
ALTER TYPE "Trade" ADD VALUE 'FIRE_SAFETY';
ALTER TYPE "Trade" ADD VALUE 'FIT_OUT_INTERIOR_DECORATION';
ALTER TYPE "Trade" ADD VALUE 'FLORIST_PLANTS';
ALTER TYPE "Trade" ADD VALUE 'FOOD_BEVERAGE';
ALTER TYPE "Trade" ADD VALUE 'FURNITURE';
ALTER TYPE "Trade" ADD VALUE 'GAS_PIPING_SYSTEMS';
ALTER TYPE "Trade" ADD VALUE 'GENERAL_TRADING';
ALTER TYPE "Trade" ADD VALUE 'GLAZING_ALUMINIUM';
ALTER TYPE "Trade" ADD VALUE 'HVAC_REFRIGERATION';
ALTER TYPE "Trade" ADD VALUE 'HARDWARE_IRONMONGERY';
ALTER TYPE "Trade" ADD VALUE 'HOTEL_HOSPITALITY';
ALTER TYPE "Trade" ADD VALUE 'INSULATION_WATERPROOFING';
ALTER TYPE "Trade" ADD VALUE 'JOINERY_CARPENTRY';
ALTER TYPE "Trade" ADD VALUE 'KITCHENS_APPLIANCES';
ALTER TYPE "Trade" ADD VALUE 'LANDSCAPING_POOLS';
ALTER TYPE "Trade" ADD VALUE 'LIFTS_ESCALATORS';
ALTER TYPE "Trade" ADD VALUE 'LIGHTING';
ALTER TYPE "Trade" ADD VALUE 'LOGISTICS_TRANSPORT';
ALTER TYPE "Trade" ADD VALUE 'MEP_ELECTROMECHANICAL';
ALTER TYPE "Trade" ADD VALUE 'MANPOWER_RECRUITMENT';
ALTER TYPE "Trade" ADD VALUE 'METAL_WORKS_FABRICATION';
ALTER TYPE "Trade" ADD VALUE 'NOT_DETERMINED';
ALTER TYPE "Trade" ADD VALUE 'OFFICE_EQUIPMENT_FURNITURE';
ALTER TYPE "Trade" ADD VALUE 'PACKAGING';
ALTER TYPE "Trade" ADD VALUE 'PAINTING_DECORATION';
ALTER TYPE "Trade" ADD VALUE 'PAINTS_COATINGS';
ALTER TYPE "Trade" ADD VALUE 'PARTITIONS_OPERABLE_WALLS';
ALTER TYPE "Trade" ADD VALUE 'PEST_CONTROL';
ALTER TYPE "Trade" ADD VALUE 'PLASTERING_TILING';
ALTER TYPE "Trade" ADD VALUE 'PLASTICS_COMPOSITES';
ALTER TYPE "Trade" ADD VALUE 'PLUMBING_SANITARYWARE';
ALTER TYPE "Trade" ADD VALUE 'PRINTING';
ALTER TYPE "Trade" ADD VALUE 'PROFESSIONAL_SERVICES';
ALTER TYPE "Trade" ADD VALUE 'REAL_ESTATE_DEVELOPMENT';
ALTER TYPE "Trade" ADD VALUE 'RETAIL_DISTRIBUTION';
ALTER TYPE "Trade" ADD VALUE 'SCAFFOLDING_ACCESS';
ALTER TYPE "Trade" ADD VALUE 'SECURITY_ELV_SYSTEMS';
ALTER TYPE "Trade" ADD VALUE 'SIGNAGE_ADVERTISING';
ALTER TYPE "Trade" ADD VALUE 'SOLID_SURFACE_WORKTOPS';
ALTER TYPE "Trade" ADD VALUE 'SPORTS_RECREATION_EQUIPMENT';
ALTER TYPE "Trade" ADD VALUE 'STEEL_STRUCTURES';
ALTER TYPE "Trade" ADD VALUE 'STONE_MARBLE_GRANITE';
ALTER TYPE "Trade" ADD VALUE 'STORAGE_RACKING';
ALTER TYPE "Trade" ADD VALUE 'TECHNICAL_SERVICES_GENERAL';
ALTER TYPE "Trade" ADD VALUE 'TESTING_INSPECTION';
ALTER TYPE "Trade" ADD VALUE 'TILES_CERAMICS';
ALTER TYPE "Trade" ADD VALUE 'TIMBER_WOOD_PRODUCTS';
ALTER TYPE "Trade" ADD VALUE 'TOOLS_MACHINERY';
ALTER TYPE "Trade" ADD VALUE 'TRAINING_HR';
ALTER TYPE "Trade" ADD VALUE 'UNIFORMS_WORKWEAR';
ALTER TYPE "Trade" ADD VALUE 'UPHOLSTERY_SOFT_FURNISHING';
ALTER TYPE "Trade" ADD VALUE 'WALLCOVERINGS';
ALTER TYPE "Trade" ADD VALUE 'WATER_TREATMENT';

