import Link from "next/link";
import { format, isPast, isToday, startOfDay } from "date-fns";
import { Calendar, ChevronDown, ChevronRight, MessageSquare, Sparkles } from "lucide-react";
import type { DeadlineRow } from "./types";

export type ColumnId = "title" | "project" | "status" | "tasks" | "notes" | "auto" | "dueDate";

export const COLUMN_LABELS: Record<ColumnId, string> = {
  title: "Deadline",
  project: "Project",
  status: "Status",
  tasks: "Tasks",
  notes: "Notes",
  auto: "Source",
  dueDate: "Due Date",
};

export const DEFAULT_COLUMNS: ColumnId[] = ["title", "project", "auto", "tasks", "dueDate"];

export const ALL_COLUMNS: ColumnId[] = ["title", "project", "status", "tasks", "notes", "auto", "dueDate"];

/** Columns rendered as inline info badges beneath the title — everything except "title" itself. */
export const META_COLUMNS = ALL_COLUMNS.filter((c) => c !== "title");

export function renderMetaItem(
  col: ColumnId,
  deadline: DeadlineRow & { _count: { taskNotes: number } },
  ctx: { expanded: boolean; onToggleExpand: () => void }
) {
  switch (col) {
    case "project":
      return deadline.pmProject ? (
        <Link key={col} href={`/pm/projects/${deadline.pmProject.id}`} className="hover:underline">
          {deadline.pmProject.title}
        </Link>
      ) : null;
    case "status":
      return (
        <span key={col} className={deadline.status === "DONE" ? "text-emerald-600" : "text-slate-500"}>
          {deadline.status === "DONE" ? "Done" : "Open"}
        </span>
      );
    case "auto":
      return deadline.autoGenerated ? (
        <span key={col} className="flex items-center gap-0.5" title="Auto-generated from submission deadline">
          <Sparkles size={11} />
          Auto
        </span>
      ) : null;
    case "notes":
      return deadline._count.taskNotes > 0 ? (
        <span key={col} className="flex items-center gap-0.5">
          <MessageSquare size={11} />
          {deadline._count.taskNotes}
        </span>
      ) : null;
    case "tasks": {
      if (deadline.subtasks.length === 0) return null;
      const doneCount = deadline.subtasks.filter((s) => s.status === "DONE").length;
      return (
        <button
          key={col}
          onClick={ctx.onToggleExpand}
          className="flex items-center gap-0.5 hover:text-slate-600"
        >
          {ctx.expanded ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
          {doneCount}/{deadline.subtasks.length} tasks
        </button>
      );
    }
    case "dueDate": {
      if (!deadline.dueDate) return null;
      const due = startOfDay(deadline.dueDate);
      const overdue = deadline.status === "OPEN" && isPast(due) && !isToday(due);
      const dueToday = isToday(due);
      return (
        <span
          key={col}
          className={`flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium ${
            overdue ? "bg-red-50 text-red-700" : dueToday ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"
          }`}
        >
          <Calendar size={11} />
          {format(due, "MMM d")}
        </span>
      );
    }
    default:
      return null;
  }
}
