"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Calendar, CheckCircle2, Circle, Sparkles, Trash2 } from "lucide-react";
import type { Project, Task } from "@prisma/client";
import { updateDeadlineStatus, updateDeadlineDueDate, deleteDeadline } from "@/lib/actions/deadlines";

function toDateInputValue(date: Date | null) {
  if (!date) return "";
  return new Date(date).toISOString().slice(0, 10);
}

export default function DeadlineHeader({ deadline, project }: { deadline: Task; project: Project | null }) {
  const [status, setStatus] = useState(deadline.status);
  const [dueDate, setDueDate] = useState(toDateInputValue(deadline.dueDate));
  const [pending, startTransition] = useTransition();
  const router = useRouter();

  function toggleStatus() {
    const next = status === "OPEN" ? "DONE" : "OPEN";
    setStatus(next);
    startTransition(() => {
      updateDeadlineStatus(deadline.id, next);
    });
  }

  function handleDueDateChange(value: string) {
    setDueDate(value);
    startTransition(() => {
      updateDeadlineDueDate(deadline.id, value || null);
    });
  }

  function handleDelete() {
    if (!confirm(`Delete "${deadline.title}"?`)) return;
    startTransition(async () => {
      await deleteDeadline(deadline.id);
      router.push("/deadlines");
    });
  }

  return (
    <div className="mb-6">
      <Link
        href="/deadlines"
        className="mb-3 inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-800"
      >
        <ArrowLeft size={15} />
        Deadlines
      </Link>

      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0">
          <div className="flex items-start gap-2.5">
            <button onClick={toggleStatus} disabled={pending} className="mt-0.5 shrink-0 text-slate-400 hover:text-slate-700">
              {status === "DONE" ? (
                <CheckCircle2 size={22} className="text-emerald-600" />
              ) : (
                <Circle size={22} />
              )}
            </button>
            <h1
              className={`text-2xl font-semibold ${
                status === "DONE" ? "text-slate-400 line-through" : "text-slate-900"
              }`}
            >
              {deadline.title}
            </h1>
          </div>
          <div className="mt-2 ml-8 flex flex-wrap items-center gap-3 text-sm text-slate-500">
            {project && (
              <Link href={`/projects/${project.id}`} className="hover:underline">
                {project.title}
              </Link>
            )}
            {deadline.autoGenerated && (
              <span className="flex items-center gap-1" title="Auto-generated from the project's submission deadline">
                <Sparkles size={13} />
                Auto-tracked deadline
              </span>
            )}
          </div>
        </div>

        <div className="flex items-center gap-2">
          <label className="flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600">
            <Calendar size={15} className="text-slate-400" />
            <input
              type="date"
              value={dueDate}
              onChange={(e) => handleDueDateChange(e.target.value)}
              className="outline-none"
            />
          </label>
          {!deadline.autoGenerated && (
            <button
              onClick={handleDelete}
              title="Delete deadline"
              className="flex items-center justify-center rounded-lg border border-slate-200 p-2 text-slate-400 transition hover:border-red-200 hover:bg-red-50 hover:text-red-600"
            >
              <Trash2 size={16} />
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
